name: action

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Update
      env:
        token: ${{ secrets.token }}
        password: ${{ secrets.password }}
      run: |
        python3 -m pip install discord pyaescrypt databases[sqlite]
        python3 script.py

    - name: Commit
      run: |
        git add database.aes
        
        git config --local user.email "ollybotting"
        git config --local user.name "ollybotting"
        
        git commit -m update -a --amend

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
